#! /usr/bin/env php
<?php

use App\SayHelloCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Application('Hello world demo', '1.1');

$app->add(new SayHelloCommand());

$app->run();

// laravel new app
// Add entry to hosts file
// Add entry to httpd-vhost.conf file
// restart apache service.
